# Generated by Django 3.2.15 on 2023-03-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='start_time',
        ),
    ]
