# Generated by Django 3.2.15 on 2023-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tickets', '0002_auto_20230329_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='available_seats',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
