# Generated by Django 3.2.15 on 2023-03-29 16:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tickets', '0003_showtime_available_seats'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='showtime',
            managers=[
                ('model', django.db.models.manager.Manager()),
            ],
        ),
    ]
