# Generated by Django 3.2.15 on 2023-03-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tickets', '0004_alter_showtime_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='showtime',
            managers=[
            ],
        ),
    ]
